version: "3.8"

services:

  redis:
    image: redis
    container_name: redis
    networks:
      - admin_panel
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - admin_panel
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      #PGDATA: /data/db/postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    networks:
      - admin_panel
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      #ES_JAVA_OPTS: -Xms2G -Xmx2G
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: trucktrace

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    depends_on:
      - elasticsearch
    networks:
      - admin_panel
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: admin
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200


networks:
  admin_panel:
    name: admin_panel
