version: "3.8"

services:

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass redis_QRTASFXVF
    networks:
      - admin_panel
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - admin_panel
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      #PGDATA: /data/db/postgres

networks:
  admin_panel:
    name: admin_panel
